fragment HjemParts on Hjem {
  __typename
  heading
  deck
  byline
  intro
  bodyText1
  bodyText2
  pullQuote
  cards {
    __typename
    title
    link
    description
  }
  dampskipHeading
  dampskipText
  dampskipImage
  dampskipImageAlt
  dampskipImageCaption
  dampskipFotefarText
  noticeTitle
  noticeText
  testimonials {
    __typename
    quote
    source
  }
}

fragment HistorieParts on Historie {
  __typename
  heading
  deck
  byline
  intro
  introBody
  pullQuote1
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
}

fragment KontaktParts on Kontakt {
  __typename
  heading
  deck
  byline
  intro
  contacts {
    __typename
    name
    email
    phone
  }
  generalEmail
  businessName
  addressLine1
  addressLine2
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
}

fragment ServeringParts on Servering {
  __typename
  heading
  deck
  byline
  intro
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
  noticeTitle
  noticeText
}

fragment KulturformidlingParts on Kulturformidling {
  __typename
  heading
  deck
  byline
  intro
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
  noticeTitle
  noticeText
}

fragment ArkivParts on Arkiv {
  __typename
  heading
  deck
  byline
  intro
  gallerySections {
    __typename
    heading
    description
    photoCredit
    images {
      __typename
      image
      alt
      caption
    }
  }
}

fragment RestaureringParts on Restaurering {
  __typename
  heading
  deck
  byline
  intro
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
}

fragment HjemEnParts on HjemEn {
  __typename
  heading
  deck
  byline
  intro
  bodyText1
  bodyText2
  pullQuote
  cards {
    __typename
    title
    link
    description
  }
  dampskipHeading
  dampskipText
  dampskipImage
  dampskipImageAlt
  dampskipImageCaption
  dampskipFotefarText
  noticeTitle
  noticeText
  testimonials {
    __typename
    quote
    source
  }
}

fragment HistorieEnParts on HistorieEn {
  __typename
  heading
  deck
  byline
  intro
  introBody
  pullQuote1
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
}

fragment KontaktEnParts on KontaktEn {
  __typename
  heading
  deck
  byline
  intro
  contacts {
    __typename
    name
    email
    phone
  }
  generalEmail
  businessName
  addressLine1
  addressLine2
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
}

fragment ServeringEnParts on ServeringEn {
  __typename
  heading
  deck
  byline
  intro
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
  noticeTitle
  noticeText
}

fragment KulturformidlingEnParts on KulturformidlingEn {
  __typename
  heading
  deck
  byline
  intro
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
  noticeTitle
  noticeText
}

fragment ArkivEnParts on ArkivEn {
  __typename
  heading
  deck
  byline
  intro
  gallerySections {
    __typename
    heading
    description
    photoCredit
    images {
      __typename
      image
      alt
      caption
    }
  }
}

fragment RestaureringEnParts on RestaureringEn {
  __typename
  heading
  deck
  byline
  intro
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
}

fragment ReferanserParts on Referanser {
  __typename
  quote
  source
  date
  context
  sortOrder
}

fragment NyheterParts on Nyheter {
  __typename
  title
  deck
  byline
  date
  intro
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
  photoCredit
  galleryImages {
    __typename
    image
    alt
  }
}
