//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  hjem: Hjem;
  hjemConnection: HjemConnection;
  omOss: OmOss;
  omOssConnection: OmOssConnection;
  kontakt: Kontakt;
  kontaktConnection: KontaktConnection;
  servering: Servering;
  serveringConnection: ServeringConnection;
  overnatting: Overnatting;
  overnattingConnection: OvernattingConnection;
  kulturformidling: Kulturformidling;
  kulturformidlingConnection: KulturformidlingConnection;
  krambu: Krambu;
  krambuConnection: KrambuConnection;
  bilder: Bilder;
  bilderConnection: BilderConnection;
  referanser: Referanser;
  referanserConnection: ReferanserConnection;
  nyheter: Nyheter;
  nyheterConnection: NyheterConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHjemArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHjemConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HjemFilter>;
};


export type QueryOmOssArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOmOssConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OmOssFilter>;
};


export type QueryKontaktArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryKontaktConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<KontaktFilter>;
};


export type QueryServeringArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServeringConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServeringFilter>;
};


export type QueryOvernattingArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOvernattingConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OvernattingFilter>;
};


export type QueryKulturformidlingArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryKulturformidlingConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<KulturformidlingFilter>;
};


export type QueryKrambuArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryKrambuConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<KrambuFilter>;
};


export type QueryBilderArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBilderConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BilderFilter>;
};


export type QueryReferanserArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryReferanserConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReferanserFilter>;
};


export type QueryNyheterArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNyheterConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NyheterFilter>;
};

export type DocumentFilter = {
  hjem?: InputMaybe<HjemFilter>;
  omOss?: InputMaybe<OmOssFilter>;
  kontakt?: InputMaybe<KontaktFilter>;
  servering?: InputMaybe<ServeringFilter>;
  overnatting?: InputMaybe<OvernattingFilter>;
  kulturformidling?: InputMaybe<KulturformidlingFilter>;
  krambu?: InputMaybe<KrambuFilter>;
  bilder?: InputMaybe<BilderFilter>;
  referanser?: InputMaybe<ReferanserFilter>;
  nyheter?: InputMaybe<NyheterFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Hjem | OmOss | Kontakt | Servering | Overnatting | Kulturformidling | Krambu | Bilder | Referanser | Nyheter | Folder;

export type HjemCards = {
  __typename?: 'HjemCards';
  title?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type HjemTestimonials = {
  __typename?: 'HjemTestimonials';
  quote?: Maybe<Scalars['String']['output']>;
  source?: Maybe<Scalars['String']['output']>;
};

export type Hjem = Node & Document & {
  __typename?: 'Hjem';
  heading: Scalars['String']['output'];
  deck?: Maybe<Scalars['String']['output']>;
  byline?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  bodyText1?: Maybe<Scalars['String']['output']>;
  bodyText2?: Maybe<Scalars['String']['output']>;
  pullQuote?: Maybe<Scalars['String']['output']>;
  cards?: Maybe<Array<Maybe<HjemCards>>>;
  dampskipHeading?: Maybe<Scalars['String']['output']>;
  dampskipText?: Maybe<Scalars['String']['output']>;
  dampskipImage?: Maybe<Scalars['String']['output']>;
  dampskipImageAlt?: Maybe<Scalars['String']['output']>;
  dampskipImageCaption?: Maybe<Scalars['String']['output']>;
  dampskipFotefarText?: Maybe<Scalars['String']['output']>;
  noticeTitle?: Maybe<Scalars['String']['output']>;
  noticeText?: Maybe<Scalars['String']['output']>;
  testimonials?: Maybe<Array<Maybe<HjemTestimonials>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HjemCardsFilter = {
  title?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HjemTestimonialsFilter = {
  quote?: InputMaybe<StringFilter>;
  source?: InputMaybe<StringFilter>;
};

export type HjemFilter = {
  heading?: InputMaybe<StringFilter>;
  deck?: InputMaybe<StringFilter>;
  byline?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  bodyText1?: InputMaybe<StringFilter>;
  bodyText2?: InputMaybe<StringFilter>;
  pullQuote?: InputMaybe<StringFilter>;
  cards?: InputMaybe<HjemCardsFilter>;
  dampskipHeading?: InputMaybe<StringFilter>;
  dampskipText?: InputMaybe<StringFilter>;
  dampskipImage?: InputMaybe<ImageFilter>;
  dampskipImageAlt?: InputMaybe<StringFilter>;
  dampskipImageCaption?: InputMaybe<StringFilter>;
  dampskipFotefarText?: InputMaybe<StringFilter>;
  noticeTitle?: InputMaybe<StringFilter>;
  noticeText?: InputMaybe<StringFilter>;
  testimonials?: InputMaybe<HjemTestimonialsFilter>;
};

export type HjemConnectionEdges = {
  __typename?: 'HjemConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Hjem>;
};

export type HjemConnection = Connection & {
  __typename?: 'HjemConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HjemConnectionEdges>>>;
};

export type OmOssSections = {
  __typename?: 'OmOssSections';
  heading?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  imageCaption?: Maybe<Scalars['String']['output']>;
  pullQuote?: Maybe<Scalars['String']['output']>;
};

export type OmOss = Node & Document & {
  __typename?: 'OmOss';
  heading: Scalars['String']['output'];
  deck?: Maybe<Scalars['String']['output']>;
  byline?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  introBody?: Maybe<Scalars['String']['output']>;
  pullQuote1?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<OmOssSections>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type OmOssSectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  imageCaption?: InputMaybe<StringFilter>;
  pullQuote?: InputMaybe<StringFilter>;
};

export type OmOssFilter = {
  heading?: InputMaybe<StringFilter>;
  deck?: InputMaybe<StringFilter>;
  byline?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  introBody?: InputMaybe<StringFilter>;
  pullQuote1?: InputMaybe<StringFilter>;
  sections?: InputMaybe<OmOssSectionsFilter>;
};

export type OmOssConnectionEdges = {
  __typename?: 'OmOssConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<OmOss>;
};

export type OmOssConnection = Connection & {
  __typename?: 'OmOssConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<OmOssConnectionEdges>>>;
};

export type KontaktContacts = {
  __typename?: 'KontaktContacts';
  name?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
};

export type KontaktSections = {
  __typename?: 'KontaktSections';
  heading?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  imageCaption?: Maybe<Scalars['String']['output']>;
  pullQuote?: Maybe<Scalars['String']['output']>;
};

export type Kontakt = Node & Document & {
  __typename?: 'Kontakt';
  heading: Scalars['String']['output'];
  deck?: Maybe<Scalars['String']['output']>;
  byline?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  contacts?: Maybe<Array<Maybe<KontaktContacts>>>;
  generalEmail?: Maybe<Scalars['String']['output']>;
  businessName?: Maybe<Scalars['String']['output']>;
  addressLine1?: Maybe<Scalars['String']['output']>;
  addressLine2?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<KontaktSections>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type KontaktContactsFilter = {
  name?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
};

export type KontaktSectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  imageCaption?: InputMaybe<StringFilter>;
  pullQuote?: InputMaybe<StringFilter>;
};

export type KontaktFilter = {
  heading?: InputMaybe<StringFilter>;
  deck?: InputMaybe<StringFilter>;
  byline?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  contacts?: InputMaybe<KontaktContactsFilter>;
  generalEmail?: InputMaybe<StringFilter>;
  businessName?: InputMaybe<StringFilter>;
  addressLine1?: InputMaybe<StringFilter>;
  addressLine2?: InputMaybe<StringFilter>;
  sections?: InputMaybe<KontaktSectionsFilter>;
};

export type KontaktConnectionEdges = {
  __typename?: 'KontaktConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Kontakt>;
};

export type KontaktConnection = Connection & {
  __typename?: 'KontaktConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<KontaktConnectionEdges>>>;
};

export type ServeringSections = {
  __typename?: 'ServeringSections';
  heading?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  imageCaption?: Maybe<Scalars['String']['output']>;
  pullQuote?: Maybe<Scalars['String']['output']>;
};

export type Servering = Node & Document & {
  __typename?: 'Servering';
  heading: Scalars['String']['output'];
  deck?: Maybe<Scalars['String']['output']>;
  byline?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<ServeringSections>>>;
  noticeTitle?: Maybe<Scalars['String']['output']>;
  noticeText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServeringSectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  imageCaption?: InputMaybe<StringFilter>;
  pullQuote?: InputMaybe<StringFilter>;
};

export type ServeringFilter = {
  heading?: InputMaybe<StringFilter>;
  deck?: InputMaybe<StringFilter>;
  byline?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  sections?: InputMaybe<ServeringSectionsFilter>;
  noticeTitle?: InputMaybe<StringFilter>;
  noticeText?: InputMaybe<StringFilter>;
};

export type ServeringConnectionEdges = {
  __typename?: 'ServeringConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Servering>;
};

export type ServeringConnection = Connection & {
  __typename?: 'ServeringConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServeringConnectionEdges>>>;
};

export type OvernattingSections = {
  __typename?: 'OvernattingSections';
  heading?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  imageCaption?: Maybe<Scalars['String']['output']>;
  pullQuote?: Maybe<Scalars['String']['output']>;
};

export type OvernattingPriser = {
  __typename?: 'OvernattingPriser';
  label?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
};

export type Overnatting = Node & Document & {
  __typename?: 'Overnatting';
  heading: Scalars['String']['output'];
  deck?: Maybe<Scalars['String']['output']>;
  byline?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<OvernattingSections>>>;
  priser?: Maybe<Array<Maybe<OvernattingPriser>>>;
  prisNotat?: Maybe<Scalars['String']['output']>;
  noticeTitle?: Maybe<Scalars['String']['output']>;
  noticeText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type OvernattingSectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  imageCaption?: InputMaybe<StringFilter>;
  pullQuote?: InputMaybe<StringFilter>;
};

export type OvernattingPriserFilter = {
  label?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
};

export type OvernattingFilter = {
  heading?: InputMaybe<StringFilter>;
  deck?: InputMaybe<StringFilter>;
  byline?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  sections?: InputMaybe<OvernattingSectionsFilter>;
  priser?: InputMaybe<OvernattingPriserFilter>;
  prisNotat?: InputMaybe<StringFilter>;
  noticeTitle?: InputMaybe<StringFilter>;
  noticeText?: InputMaybe<StringFilter>;
};

export type OvernattingConnectionEdges = {
  __typename?: 'OvernattingConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Overnatting>;
};

export type OvernattingConnection = Connection & {
  __typename?: 'OvernattingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<OvernattingConnectionEdges>>>;
};

export type KulturformidlingSections = {
  __typename?: 'KulturformidlingSections';
  heading?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  imageCaption?: Maybe<Scalars['String']['output']>;
  pullQuote?: Maybe<Scalars['String']['output']>;
};

export type Kulturformidling = Node & Document & {
  __typename?: 'Kulturformidling';
  heading: Scalars['String']['output'];
  deck?: Maybe<Scalars['String']['output']>;
  byline?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<KulturformidlingSections>>>;
  noticeTitle?: Maybe<Scalars['String']['output']>;
  noticeText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type KulturformidlingSectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  imageCaption?: InputMaybe<StringFilter>;
  pullQuote?: InputMaybe<StringFilter>;
};

export type KulturformidlingFilter = {
  heading?: InputMaybe<StringFilter>;
  deck?: InputMaybe<StringFilter>;
  byline?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  sections?: InputMaybe<KulturformidlingSectionsFilter>;
  noticeTitle?: InputMaybe<StringFilter>;
  noticeText?: InputMaybe<StringFilter>;
};

export type KulturformidlingConnectionEdges = {
  __typename?: 'KulturformidlingConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Kulturformidling>;
};

export type KulturformidlingConnection = Connection & {
  __typename?: 'KulturformidlingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<KulturformidlingConnectionEdges>>>;
};

export type KrambuSections = {
  __typename?: 'KrambuSections';
  heading?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  imageCaption?: Maybe<Scalars['String']['output']>;
  pullQuote?: Maybe<Scalars['String']['output']>;
};

export type Krambu = Node & Document & {
  __typename?: 'Krambu';
  heading: Scalars['String']['output'];
  deck?: Maybe<Scalars['String']['output']>;
  byline?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<KrambuSections>>>;
  noticeTitle?: Maybe<Scalars['String']['output']>;
  noticeText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type KrambuSectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  imageCaption?: InputMaybe<StringFilter>;
  pullQuote?: InputMaybe<StringFilter>;
};

export type KrambuFilter = {
  heading?: InputMaybe<StringFilter>;
  deck?: InputMaybe<StringFilter>;
  byline?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  sections?: InputMaybe<KrambuSectionsFilter>;
  noticeTitle?: InputMaybe<StringFilter>;
  noticeText?: InputMaybe<StringFilter>;
};

export type KrambuConnectionEdges = {
  __typename?: 'KrambuConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Krambu>;
};

export type KrambuConnection = Connection & {
  __typename?: 'KrambuConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<KrambuConnectionEdges>>>;
};

export type BilderGallerySectionsImages = {
  __typename?: 'BilderGallerySectionsImages';
  image?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
};

export type BilderGallerySections = {
  __typename?: 'BilderGallerySections';
  heading?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  photoCredit?: Maybe<Scalars['String']['output']>;
  images?: Maybe<Array<Maybe<BilderGallerySectionsImages>>>;
};

export type Bilder = Node & Document & {
  __typename?: 'Bilder';
  heading: Scalars['String']['output'];
  deck?: Maybe<Scalars['String']['output']>;
  byline?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  gallerySections?: Maybe<Array<Maybe<BilderGallerySections>>>;
  restaureringHeading?: Maybe<Scalars['String']['output']>;
  restaureringText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BilderGallerySectionsImagesFilter = {
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
};

export type BilderGallerySectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  photoCredit?: InputMaybe<StringFilter>;
  images?: InputMaybe<BilderGallerySectionsImagesFilter>;
};

export type BilderFilter = {
  heading?: InputMaybe<StringFilter>;
  deck?: InputMaybe<StringFilter>;
  byline?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  gallerySections?: InputMaybe<BilderGallerySectionsFilter>;
  restaureringHeading?: InputMaybe<StringFilter>;
  restaureringText?: InputMaybe<StringFilter>;
};

export type BilderConnectionEdges = {
  __typename?: 'BilderConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Bilder>;
};

export type BilderConnection = Connection & {
  __typename?: 'BilderConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BilderConnectionEdges>>>;
};

export type Referanser = Node & Document & {
  __typename?: 'Referanser';
  quote?: Maybe<Scalars['String']['output']>;
  source: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  context?: Maybe<Scalars['String']['output']>;
  sortOrder?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ReferanserFilter = {
  quote?: InputMaybe<StringFilter>;
  source?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  context?: InputMaybe<StringFilter>;
  sortOrder?: InputMaybe<NumberFilter>;
};

export type ReferanserConnectionEdges = {
  __typename?: 'ReferanserConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Referanser>;
};

export type ReferanserConnection = Connection & {
  __typename?: 'ReferanserConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ReferanserConnectionEdges>>>;
};

export type NyheterSections = {
  __typename?: 'NyheterSections';
  heading?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  imageCaption?: Maybe<Scalars['String']['output']>;
  pullQuote?: Maybe<Scalars['String']['output']>;
};

export type NyheterGalleryImages = {
  __typename?: 'NyheterGalleryImages';
  image?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type Nyheter = Node & Document & {
  __typename?: 'Nyheter';
  title: Scalars['String']['output'];
  deck?: Maybe<Scalars['String']['output']>;
  byline?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<NyheterSections>>>;
  photoCredit?: Maybe<Scalars['String']['output']>;
  galleryImages?: Maybe<Array<Maybe<NyheterGalleryImages>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NyheterSectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  imageCaption?: InputMaybe<StringFilter>;
  pullQuote?: InputMaybe<StringFilter>;
};

export type NyheterGalleryImagesFilter = {
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type NyheterFilter = {
  title?: InputMaybe<StringFilter>;
  deck?: InputMaybe<StringFilter>;
  byline?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  sections?: InputMaybe<NyheterSectionsFilter>;
  photoCredit?: InputMaybe<StringFilter>;
  galleryImages?: InputMaybe<NyheterGalleryImagesFilter>;
};

export type NyheterConnectionEdges = {
  __typename?: 'NyheterConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Nyheter>;
};

export type NyheterConnection = Connection & {
  __typename?: 'NyheterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NyheterConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHjem: Hjem;
  createHjem: Hjem;
  updateOmOss: OmOss;
  createOmOss: OmOss;
  updateKontakt: Kontakt;
  createKontakt: Kontakt;
  updateServering: Servering;
  createServering: Servering;
  updateOvernatting: Overnatting;
  createOvernatting: Overnatting;
  updateKulturformidling: Kulturformidling;
  createKulturformidling: Kulturformidling;
  updateKrambu: Krambu;
  createKrambu: Krambu;
  updateBilder: Bilder;
  createBilder: Bilder;
  updateReferanser: Referanser;
  createReferanser: Referanser;
  updateNyheter: Nyheter;
  createNyheter: Nyheter;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHjemArgs = {
  relativePath: Scalars['String']['input'];
  params: HjemMutation;
};


export type MutationCreateHjemArgs = {
  relativePath: Scalars['String']['input'];
  params: HjemMutation;
};


export type MutationUpdateOmOssArgs = {
  relativePath: Scalars['String']['input'];
  params: OmOssMutation;
};


export type MutationCreateOmOssArgs = {
  relativePath: Scalars['String']['input'];
  params: OmOssMutation;
};


export type MutationUpdateKontaktArgs = {
  relativePath: Scalars['String']['input'];
  params: KontaktMutation;
};


export type MutationCreateKontaktArgs = {
  relativePath: Scalars['String']['input'];
  params: KontaktMutation;
};


export type MutationUpdateServeringArgs = {
  relativePath: Scalars['String']['input'];
  params: ServeringMutation;
};


export type MutationCreateServeringArgs = {
  relativePath: Scalars['String']['input'];
  params: ServeringMutation;
};


export type MutationUpdateOvernattingArgs = {
  relativePath: Scalars['String']['input'];
  params: OvernattingMutation;
};


export type MutationCreateOvernattingArgs = {
  relativePath: Scalars['String']['input'];
  params: OvernattingMutation;
};


export type MutationUpdateKulturformidlingArgs = {
  relativePath: Scalars['String']['input'];
  params: KulturformidlingMutation;
};


export type MutationCreateKulturformidlingArgs = {
  relativePath: Scalars['String']['input'];
  params: KulturformidlingMutation;
};


export type MutationUpdateKrambuArgs = {
  relativePath: Scalars['String']['input'];
  params: KrambuMutation;
};


export type MutationCreateKrambuArgs = {
  relativePath: Scalars['String']['input'];
  params: KrambuMutation;
};


export type MutationUpdateBilderArgs = {
  relativePath: Scalars['String']['input'];
  params: BilderMutation;
};


export type MutationCreateBilderArgs = {
  relativePath: Scalars['String']['input'];
  params: BilderMutation;
};


export type MutationUpdateReferanserArgs = {
  relativePath: Scalars['String']['input'];
  params: ReferanserMutation;
};


export type MutationCreateReferanserArgs = {
  relativePath: Scalars['String']['input'];
  params: ReferanserMutation;
};


export type MutationUpdateNyheterArgs = {
  relativePath: Scalars['String']['input'];
  params: NyheterMutation;
};


export type MutationCreateNyheterArgs = {
  relativePath: Scalars['String']['input'];
  params: NyheterMutation;
};

export type DocumentUpdateMutation = {
  hjem?: InputMaybe<HjemMutation>;
  omOss?: InputMaybe<OmOssMutation>;
  kontakt?: InputMaybe<KontaktMutation>;
  servering?: InputMaybe<ServeringMutation>;
  overnatting?: InputMaybe<OvernattingMutation>;
  kulturformidling?: InputMaybe<KulturformidlingMutation>;
  krambu?: InputMaybe<KrambuMutation>;
  bilder?: InputMaybe<BilderMutation>;
  referanser?: InputMaybe<ReferanserMutation>;
  nyheter?: InputMaybe<NyheterMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  hjem?: InputMaybe<HjemMutation>;
  omOss?: InputMaybe<OmOssMutation>;
  kontakt?: InputMaybe<KontaktMutation>;
  servering?: InputMaybe<ServeringMutation>;
  overnatting?: InputMaybe<OvernattingMutation>;
  kulturformidling?: InputMaybe<KulturformidlingMutation>;
  krambu?: InputMaybe<KrambuMutation>;
  bilder?: InputMaybe<BilderMutation>;
  referanser?: InputMaybe<ReferanserMutation>;
  nyheter?: InputMaybe<NyheterMutation>;
};

export type HjemCardsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type HjemTestimonialsMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  source?: InputMaybe<Scalars['String']['input']>;
};

export type HjemMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  deck?: InputMaybe<Scalars['String']['input']>;
  byline?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  bodyText1?: InputMaybe<Scalars['String']['input']>;
  bodyText2?: InputMaybe<Scalars['String']['input']>;
  pullQuote?: InputMaybe<Scalars['String']['input']>;
  cards?: InputMaybe<Array<InputMaybe<HjemCardsMutation>>>;
  dampskipHeading?: InputMaybe<Scalars['String']['input']>;
  dampskipText?: InputMaybe<Scalars['String']['input']>;
  dampskipImage?: InputMaybe<Scalars['String']['input']>;
  dampskipImageAlt?: InputMaybe<Scalars['String']['input']>;
  dampskipImageCaption?: InputMaybe<Scalars['String']['input']>;
  dampskipFotefarText?: InputMaybe<Scalars['String']['input']>;
  noticeTitle?: InputMaybe<Scalars['String']['input']>;
  noticeText?: InputMaybe<Scalars['String']['input']>;
  testimonials?: InputMaybe<Array<InputMaybe<HjemTestimonialsMutation>>>;
};

export type OmOssSectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  imageCaption?: InputMaybe<Scalars['String']['input']>;
  pullQuote?: InputMaybe<Scalars['String']['input']>;
};

export type OmOssMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  deck?: InputMaybe<Scalars['String']['input']>;
  byline?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  introBody?: InputMaybe<Scalars['String']['input']>;
  pullQuote1?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<OmOssSectionsMutation>>>;
};

export type KontaktContactsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
};

export type KontaktSectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  imageCaption?: InputMaybe<Scalars['String']['input']>;
  pullQuote?: InputMaybe<Scalars['String']['input']>;
};

export type KontaktMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  deck?: InputMaybe<Scalars['String']['input']>;
  byline?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  contacts?: InputMaybe<Array<InputMaybe<KontaktContactsMutation>>>;
  generalEmail?: InputMaybe<Scalars['String']['input']>;
  businessName?: InputMaybe<Scalars['String']['input']>;
  addressLine1?: InputMaybe<Scalars['String']['input']>;
  addressLine2?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<KontaktSectionsMutation>>>;
};

export type ServeringSectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  imageCaption?: InputMaybe<Scalars['String']['input']>;
  pullQuote?: InputMaybe<Scalars['String']['input']>;
};

export type ServeringMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  deck?: InputMaybe<Scalars['String']['input']>;
  byline?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<ServeringSectionsMutation>>>;
  noticeTitle?: InputMaybe<Scalars['String']['input']>;
  noticeText?: InputMaybe<Scalars['String']['input']>;
};

export type OvernattingSectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  imageCaption?: InputMaybe<Scalars['String']['input']>;
  pullQuote?: InputMaybe<Scalars['String']['input']>;
};

export type OvernattingPriserMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
};

export type OvernattingMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  deck?: InputMaybe<Scalars['String']['input']>;
  byline?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<OvernattingSectionsMutation>>>;
  priser?: InputMaybe<Array<InputMaybe<OvernattingPriserMutation>>>;
  prisNotat?: InputMaybe<Scalars['String']['input']>;
  noticeTitle?: InputMaybe<Scalars['String']['input']>;
  noticeText?: InputMaybe<Scalars['String']['input']>;
};

export type KulturformidlingSectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  imageCaption?: InputMaybe<Scalars['String']['input']>;
  pullQuote?: InputMaybe<Scalars['String']['input']>;
};

export type KulturformidlingMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  deck?: InputMaybe<Scalars['String']['input']>;
  byline?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<KulturformidlingSectionsMutation>>>;
  noticeTitle?: InputMaybe<Scalars['String']['input']>;
  noticeText?: InputMaybe<Scalars['String']['input']>;
};

export type KrambuSectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  imageCaption?: InputMaybe<Scalars['String']['input']>;
  pullQuote?: InputMaybe<Scalars['String']['input']>;
};

export type KrambuMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  deck?: InputMaybe<Scalars['String']['input']>;
  byline?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<KrambuSectionsMutation>>>;
  noticeTitle?: InputMaybe<Scalars['String']['input']>;
  noticeText?: InputMaybe<Scalars['String']['input']>;
};

export type BilderGallerySectionsImagesMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
};

export type BilderGallerySectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  photoCredit?: InputMaybe<Scalars['String']['input']>;
  images?: InputMaybe<Array<InputMaybe<BilderGallerySectionsImagesMutation>>>;
};

export type BilderMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  deck?: InputMaybe<Scalars['String']['input']>;
  byline?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  gallerySections?: InputMaybe<Array<InputMaybe<BilderGallerySectionsMutation>>>;
  restaureringHeading?: InputMaybe<Scalars['String']['input']>;
  restaureringText?: InputMaybe<Scalars['String']['input']>;
};

export type ReferanserMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  source?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  context?: InputMaybe<Scalars['String']['input']>;
  sortOrder?: InputMaybe<Scalars['Float']['input']>;
};

export type NyheterSectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  imageCaption?: InputMaybe<Scalars['String']['input']>;
  pullQuote?: InputMaybe<Scalars['String']['input']>;
};

export type NyheterGalleryImagesMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type NyheterMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  deck?: InputMaybe<Scalars['String']['input']>;
  byline?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<NyheterSectionsMutation>>>;
  photoCredit?: InputMaybe<Scalars['String']['input']>;
  galleryImages?: InputMaybe<Array<InputMaybe<NyheterGalleryImagesMutation>>>;
};

export type HjemPartsFragment = { __typename: 'Hjem', heading: string, deck?: string | null, byline?: string | null, intro?: string | null, bodyText1?: string | null, bodyText2?: string | null, pullQuote?: string | null, dampskipHeading?: string | null, dampskipText?: string | null, dampskipImage?: string | null, dampskipImageAlt?: string | null, dampskipImageCaption?: string | null, dampskipFotefarText?: string | null, noticeTitle?: string | null, noticeText?: string | null, cards?: Array<{ __typename: 'HjemCards', title?: string | null, link?: string | null, description?: string | null } | null> | null, testimonials?: Array<{ __typename: 'HjemTestimonials', quote?: string | null, source?: string | null } | null> | null };

export type OmOssPartsFragment = { __typename: 'OmOss', heading: string, deck?: string | null, byline?: string | null, intro?: string | null, introBody?: string | null, pullQuote1?: string | null, sections?: Array<{ __typename: 'OmOssSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null };

export type KontaktPartsFragment = { __typename: 'Kontakt', heading: string, deck?: string | null, byline?: string | null, intro?: string | null, generalEmail?: string | null, businessName?: string | null, addressLine1?: string | null, addressLine2?: string | null, contacts?: Array<{ __typename: 'KontaktContacts', name?: string | null, email?: string | null, phone?: string | null } | null> | null, sections?: Array<{ __typename: 'KontaktSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null };

export type ServeringPartsFragment = { __typename: 'Servering', heading: string, deck?: string | null, byline?: string | null, intro?: string | null, noticeTitle?: string | null, noticeText?: string | null, sections?: Array<{ __typename: 'ServeringSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null };

export type OvernattingPartsFragment = { __typename: 'Overnatting', heading: string, deck?: string | null, byline?: string | null, intro?: string | null, prisNotat?: string | null, noticeTitle?: string | null, noticeText?: string | null, sections?: Array<{ __typename: 'OvernattingSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null, priser?: Array<{ __typename: 'OvernattingPriser', label?: string | null, price?: string | null } | null> | null };

export type KulturformidlingPartsFragment = { __typename: 'Kulturformidling', heading: string, deck?: string | null, byline?: string | null, intro?: string | null, noticeTitle?: string | null, noticeText?: string | null, sections?: Array<{ __typename: 'KulturformidlingSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null };

export type KrambuPartsFragment = { __typename: 'Krambu', heading: string, deck?: string | null, byline?: string | null, intro?: string | null, noticeTitle?: string | null, noticeText?: string | null, sections?: Array<{ __typename: 'KrambuSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null };

export type BilderPartsFragment = { __typename: 'Bilder', heading: string, deck?: string | null, byline?: string | null, intro?: string | null, restaureringHeading?: string | null, restaureringText?: string | null, gallerySections?: Array<{ __typename: 'BilderGallerySections', heading?: string | null, description?: string | null, photoCredit?: string | null, images?: Array<{ __typename: 'BilderGallerySectionsImages', image?: string | null, alt?: string | null, caption?: string | null } | null> | null } | null> | null };

export type ReferanserPartsFragment = { __typename: 'Referanser', quote?: string | null, source: string, date?: string | null, context?: string | null, sortOrder?: number | null };

export type NyheterPartsFragment = { __typename: 'Nyheter', title: string, deck?: string | null, byline?: string | null, date?: string | null, intro?: string | null, photoCredit?: string | null, sections?: Array<{ __typename: 'NyheterSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null, galleryImages?: Array<{ __typename: 'NyheterGalleryImages', image?: string | null, alt?: string | null } | null> | null };

export type HjemQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HjemQuery = { __typename?: 'Query', hjem: { __typename: 'Hjem', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, bodyText1?: string | null, bodyText2?: string | null, pullQuote?: string | null, dampskipHeading?: string | null, dampskipText?: string | null, dampskipImage?: string | null, dampskipImageAlt?: string | null, dampskipImageCaption?: string | null, dampskipFotefarText?: string | null, noticeTitle?: string | null, noticeText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, cards?: Array<{ __typename: 'HjemCards', title?: string | null, link?: string | null, description?: string | null } | null> | null, testimonials?: Array<{ __typename: 'HjemTestimonials', quote?: string | null, source?: string | null } | null> | null } };

export type HjemConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HjemFilter>;
}>;


export type HjemConnectionQuery = { __typename?: 'Query', hjemConnection: { __typename?: 'HjemConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HjemConnectionEdges', cursor: string, node?: { __typename: 'Hjem', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, bodyText1?: string | null, bodyText2?: string | null, pullQuote?: string | null, dampskipHeading?: string | null, dampskipText?: string | null, dampskipImage?: string | null, dampskipImageAlt?: string | null, dampskipImageCaption?: string | null, dampskipFotefarText?: string | null, noticeTitle?: string | null, noticeText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, cards?: Array<{ __typename: 'HjemCards', title?: string | null, link?: string | null, description?: string | null } | null> | null, testimonials?: Array<{ __typename: 'HjemTestimonials', quote?: string | null, source?: string | null } | null> | null } | null } | null> | null } };

export type OmOssQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type OmOssQuery = { __typename?: 'Query', omOss: { __typename: 'OmOss', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, introBody?: string | null, pullQuote1?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'OmOssSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null } };

export type OmOssConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OmOssFilter>;
}>;


export type OmOssConnectionQuery = { __typename?: 'Query', omOssConnection: { __typename?: 'OmOssConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'OmOssConnectionEdges', cursor: string, node?: { __typename: 'OmOss', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, introBody?: string | null, pullQuote1?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'OmOssSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null } | null } | null> | null } };

export type KontaktQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type KontaktQuery = { __typename?: 'Query', kontakt: { __typename: 'Kontakt', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, generalEmail?: string | null, businessName?: string | null, addressLine1?: string | null, addressLine2?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, contacts?: Array<{ __typename: 'KontaktContacts', name?: string | null, email?: string | null, phone?: string | null } | null> | null, sections?: Array<{ __typename: 'KontaktSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null } };

export type KontaktConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<KontaktFilter>;
}>;


export type KontaktConnectionQuery = { __typename?: 'Query', kontaktConnection: { __typename?: 'KontaktConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'KontaktConnectionEdges', cursor: string, node?: { __typename: 'Kontakt', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, generalEmail?: string | null, businessName?: string | null, addressLine1?: string | null, addressLine2?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, contacts?: Array<{ __typename: 'KontaktContacts', name?: string | null, email?: string | null, phone?: string | null } | null> | null, sections?: Array<{ __typename: 'KontaktSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null } | null } | null> | null } };

export type ServeringQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServeringQuery = { __typename?: 'Query', servering: { __typename: 'Servering', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, noticeTitle?: string | null, noticeText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'ServeringSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null } };

export type ServeringConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServeringFilter>;
}>;


export type ServeringConnectionQuery = { __typename?: 'Query', serveringConnection: { __typename?: 'ServeringConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServeringConnectionEdges', cursor: string, node?: { __typename: 'Servering', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, noticeTitle?: string | null, noticeText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'ServeringSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null } | null } | null> | null } };

export type OvernattingQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type OvernattingQuery = { __typename?: 'Query', overnatting: { __typename: 'Overnatting', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, prisNotat?: string | null, noticeTitle?: string | null, noticeText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'OvernattingSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null, priser?: Array<{ __typename: 'OvernattingPriser', label?: string | null, price?: string | null } | null> | null } };

export type OvernattingConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OvernattingFilter>;
}>;


export type OvernattingConnectionQuery = { __typename?: 'Query', overnattingConnection: { __typename?: 'OvernattingConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'OvernattingConnectionEdges', cursor: string, node?: { __typename: 'Overnatting', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, prisNotat?: string | null, noticeTitle?: string | null, noticeText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'OvernattingSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null, priser?: Array<{ __typename: 'OvernattingPriser', label?: string | null, price?: string | null } | null> | null } | null } | null> | null } };

export type KulturformidlingQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type KulturformidlingQuery = { __typename?: 'Query', kulturformidling: { __typename: 'Kulturformidling', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, noticeTitle?: string | null, noticeText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'KulturformidlingSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null } };

export type KulturformidlingConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<KulturformidlingFilter>;
}>;


export type KulturformidlingConnectionQuery = { __typename?: 'Query', kulturformidlingConnection: { __typename?: 'KulturformidlingConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'KulturformidlingConnectionEdges', cursor: string, node?: { __typename: 'Kulturformidling', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, noticeTitle?: string | null, noticeText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'KulturformidlingSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null } | null } | null> | null } };

export type KrambuQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type KrambuQuery = { __typename?: 'Query', krambu: { __typename: 'Krambu', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, noticeTitle?: string | null, noticeText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'KrambuSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null } };

export type KrambuConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<KrambuFilter>;
}>;


export type KrambuConnectionQuery = { __typename?: 'Query', krambuConnection: { __typename?: 'KrambuConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'KrambuConnectionEdges', cursor: string, node?: { __typename: 'Krambu', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, noticeTitle?: string | null, noticeText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'KrambuSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null } | null } | null> | null } };

export type BilderQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BilderQuery = { __typename?: 'Query', bilder: { __typename: 'Bilder', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, restaureringHeading?: string | null, restaureringText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, gallerySections?: Array<{ __typename: 'BilderGallerySections', heading?: string | null, description?: string | null, photoCredit?: string | null, images?: Array<{ __typename: 'BilderGallerySectionsImages', image?: string | null, alt?: string | null, caption?: string | null } | null> | null } | null> | null } };

export type BilderConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BilderFilter>;
}>;


export type BilderConnectionQuery = { __typename?: 'Query', bilderConnection: { __typename?: 'BilderConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BilderConnectionEdges', cursor: string, node?: { __typename: 'Bilder', id: string, heading: string, deck?: string | null, byline?: string | null, intro?: string | null, restaureringHeading?: string | null, restaureringText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, gallerySections?: Array<{ __typename: 'BilderGallerySections', heading?: string | null, description?: string | null, photoCredit?: string | null, images?: Array<{ __typename: 'BilderGallerySectionsImages', image?: string | null, alt?: string | null, caption?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type ReferanserQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ReferanserQuery = { __typename?: 'Query', referanser: { __typename: 'Referanser', id: string, quote?: string | null, source: string, date?: string | null, context?: string | null, sortOrder?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ReferanserConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReferanserFilter>;
}>;


export type ReferanserConnectionQuery = { __typename?: 'Query', referanserConnection: { __typename?: 'ReferanserConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ReferanserConnectionEdges', cursor: string, node?: { __typename: 'Referanser', id: string, quote?: string | null, source: string, date?: string | null, context?: string | null, sortOrder?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type NyheterQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NyheterQuery = { __typename?: 'Query', nyheter: { __typename: 'Nyheter', id: string, title: string, deck?: string | null, byline?: string | null, date?: string | null, intro?: string | null, photoCredit?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'NyheterSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null, galleryImages?: Array<{ __typename: 'NyheterGalleryImages', image?: string | null, alt?: string | null } | null> | null } };

export type NyheterConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NyheterFilter>;
}>;


export type NyheterConnectionQuery = { __typename?: 'Query', nyheterConnection: { __typename?: 'NyheterConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NyheterConnectionEdges', cursor: string, node?: { __typename: 'Nyheter', id: string, title: string, deck?: string | null, byline?: string | null, date?: string | null, intro?: string | null, photoCredit?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'NyheterSections', heading?: string | null, content?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, pullQuote?: string | null } | null> | null, galleryImages?: Array<{ __typename: 'NyheterGalleryImages', image?: string | null, alt?: string | null } | null> | null } | null } | null> | null } };

export const HjemPartsFragmentDoc = gql`
    fragment HjemParts on Hjem {
  __typename
  heading
  deck
  byline
  intro
  bodyText1
  bodyText2
  pullQuote
  cards {
    __typename
    title
    link
    description
  }
  dampskipHeading
  dampskipText
  dampskipImage
  dampskipImageAlt
  dampskipImageCaption
  dampskipFotefarText
  noticeTitle
  noticeText
  testimonials {
    __typename
    quote
    source
  }
}
    `;
export const OmOssPartsFragmentDoc = gql`
    fragment OmOssParts on OmOss {
  __typename
  heading
  deck
  byline
  intro
  introBody
  pullQuote1
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
}
    `;
export const KontaktPartsFragmentDoc = gql`
    fragment KontaktParts on Kontakt {
  __typename
  heading
  deck
  byline
  intro
  contacts {
    __typename
    name
    email
    phone
  }
  generalEmail
  businessName
  addressLine1
  addressLine2
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
}
    `;
export const ServeringPartsFragmentDoc = gql`
    fragment ServeringParts on Servering {
  __typename
  heading
  deck
  byline
  intro
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
  noticeTitle
  noticeText
}
    `;
export const OvernattingPartsFragmentDoc = gql`
    fragment OvernattingParts on Overnatting {
  __typename
  heading
  deck
  byline
  intro
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
  priser {
    __typename
    label
    price
  }
  prisNotat
  noticeTitle
  noticeText
}
    `;
export const KulturformidlingPartsFragmentDoc = gql`
    fragment KulturformidlingParts on Kulturformidling {
  __typename
  heading
  deck
  byline
  intro
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
  noticeTitle
  noticeText
}
    `;
export const KrambuPartsFragmentDoc = gql`
    fragment KrambuParts on Krambu {
  __typename
  heading
  deck
  byline
  intro
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
  noticeTitle
  noticeText
}
    `;
export const BilderPartsFragmentDoc = gql`
    fragment BilderParts on Bilder {
  __typename
  heading
  deck
  byline
  intro
  gallerySections {
    __typename
    heading
    description
    photoCredit
    images {
      __typename
      image
      alt
      caption
    }
  }
  restaureringHeading
  restaureringText
}
    `;
export const ReferanserPartsFragmentDoc = gql`
    fragment ReferanserParts on Referanser {
  __typename
  quote
  source
  date
  context
  sortOrder
}
    `;
export const NyheterPartsFragmentDoc = gql`
    fragment NyheterParts on Nyheter {
  __typename
  title
  deck
  byline
  date
  intro
  sections {
    __typename
    heading
    content
    image
    imageAlt
    imageCaption
    pullQuote
  }
  photoCredit
  galleryImages {
    __typename
    image
    alt
  }
}
    `;
export const HjemDocument = gql`
    query hjem($relativePath: String!) {
  hjem(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HjemParts
  }
}
    ${HjemPartsFragmentDoc}`;
export const HjemConnectionDocument = gql`
    query hjemConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HjemFilter) {
  hjemConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HjemParts
      }
    }
  }
}
    ${HjemPartsFragmentDoc}`;
export const OmOssDocument = gql`
    query omOss($relativePath: String!) {
  omOss(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...OmOssParts
  }
}
    ${OmOssPartsFragmentDoc}`;
export const OmOssConnectionDocument = gql`
    query omOssConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: OmOssFilter) {
  omOssConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...OmOssParts
      }
    }
  }
}
    ${OmOssPartsFragmentDoc}`;
export const KontaktDocument = gql`
    query kontakt($relativePath: String!) {
  kontakt(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...KontaktParts
  }
}
    ${KontaktPartsFragmentDoc}`;
export const KontaktConnectionDocument = gql`
    query kontaktConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: KontaktFilter) {
  kontaktConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...KontaktParts
      }
    }
  }
}
    ${KontaktPartsFragmentDoc}`;
export const ServeringDocument = gql`
    query servering($relativePath: String!) {
  servering(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServeringParts
  }
}
    ${ServeringPartsFragmentDoc}`;
export const ServeringConnectionDocument = gql`
    query serveringConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServeringFilter) {
  serveringConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServeringParts
      }
    }
  }
}
    ${ServeringPartsFragmentDoc}`;
export const OvernattingDocument = gql`
    query overnatting($relativePath: String!) {
  overnatting(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...OvernattingParts
  }
}
    ${OvernattingPartsFragmentDoc}`;
export const OvernattingConnectionDocument = gql`
    query overnattingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: OvernattingFilter) {
  overnattingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...OvernattingParts
      }
    }
  }
}
    ${OvernattingPartsFragmentDoc}`;
export const KulturformidlingDocument = gql`
    query kulturformidling($relativePath: String!) {
  kulturformidling(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...KulturformidlingParts
  }
}
    ${KulturformidlingPartsFragmentDoc}`;
export const KulturformidlingConnectionDocument = gql`
    query kulturformidlingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: KulturformidlingFilter) {
  kulturformidlingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...KulturformidlingParts
      }
    }
  }
}
    ${KulturformidlingPartsFragmentDoc}`;
export const KrambuDocument = gql`
    query krambu($relativePath: String!) {
  krambu(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...KrambuParts
  }
}
    ${KrambuPartsFragmentDoc}`;
export const KrambuConnectionDocument = gql`
    query krambuConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: KrambuFilter) {
  krambuConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...KrambuParts
      }
    }
  }
}
    ${KrambuPartsFragmentDoc}`;
export const BilderDocument = gql`
    query bilder($relativePath: String!) {
  bilder(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BilderParts
  }
}
    ${BilderPartsFragmentDoc}`;
export const BilderConnectionDocument = gql`
    query bilderConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BilderFilter) {
  bilderConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BilderParts
      }
    }
  }
}
    ${BilderPartsFragmentDoc}`;
export const ReferanserDocument = gql`
    query referanser($relativePath: String!) {
  referanser(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ReferanserParts
  }
}
    ${ReferanserPartsFragmentDoc}`;
export const ReferanserConnectionDocument = gql`
    query referanserConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ReferanserFilter) {
  referanserConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ReferanserParts
      }
    }
  }
}
    ${ReferanserPartsFragmentDoc}`;
export const NyheterDocument = gql`
    query nyheter($relativePath: String!) {
  nyheter(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NyheterParts
  }
}
    ${NyheterPartsFragmentDoc}`;
export const NyheterConnectionDocument = gql`
    query nyheterConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NyheterFilter) {
  nyheterConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NyheterParts
      }
    }
  }
}
    ${NyheterPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      hjem(variables: HjemQueryVariables, options?: C): Promise<{data: HjemQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HjemQueryVariables, query: string}> {
        return requester<{data: HjemQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HjemQueryVariables, query: string}, HjemQueryVariables>(HjemDocument, variables, options);
      },
    hjemConnection(variables?: HjemConnectionQueryVariables, options?: C): Promise<{data: HjemConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HjemConnectionQueryVariables, query: string}> {
        return requester<{data: HjemConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HjemConnectionQueryVariables, query: string}, HjemConnectionQueryVariables>(HjemConnectionDocument, variables, options);
      },
    omOss(variables: OmOssQueryVariables, options?: C): Promise<{data: OmOssQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OmOssQueryVariables, query: string}> {
        return requester<{data: OmOssQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OmOssQueryVariables, query: string}, OmOssQueryVariables>(OmOssDocument, variables, options);
      },
    omOssConnection(variables?: OmOssConnectionQueryVariables, options?: C): Promise<{data: OmOssConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OmOssConnectionQueryVariables, query: string}> {
        return requester<{data: OmOssConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OmOssConnectionQueryVariables, query: string}, OmOssConnectionQueryVariables>(OmOssConnectionDocument, variables, options);
      },
    kontakt(variables: KontaktQueryVariables, options?: C): Promise<{data: KontaktQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KontaktQueryVariables, query: string}> {
        return requester<{data: KontaktQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KontaktQueryVariables, query: string}, KontaktQueryVariables>(KontaktDocument, variables, options);
      },
    kontaktConnection(variables?: KontaktConnectionQueryVariables, options?: C): Promise<{data: KontaktConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KontaktConnectionQueryVariables, query: string}> {
        return requester<{data: KontaktConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KontaktConnectionQueryVariables, query: string}, KontaktConnectionQueryVariables>(KontaktConnectionDocument, variables, options);
      },
    servering(variables: ServeringQueryVariables, options?: C): Promise<{data: ServeringQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServeringQueryVariables, query: string}> {
        return requester<{data: ServeringQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServeringQueryVariables, query: string}, ServeringQueryVariables>(ServeringDocument, variables, options);
      },
    serveringConnection(variables?: ServeringConnectionQueryVariables, options?: C): Promise<{data: ServeringConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServeringConnectionQueryVariables, query: string}> {
        return requester<{data: ServeringConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServeringConnectionQueryVariables, query: string}, ServeringConnectionQueryVariables>(ServeringConnectionDocument, variables, options);
      },
    overnatting(variables: OvernattingQueryVariables, options?: C): Promise<{data: OvernattingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OvernattingQueryVariables, query: string}> {
        return requester<{data: OvernattingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OvernattingQueryVariables, query: string}, OvernattingQueryVariables>(OvernattingDocument, variables, options);
      },
    overnattingConnection(variables?: OvernattingConnectionQueryVariables, options?: C): Promise<{data: OvernattingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OvernattingConnectionQueryVariables, query: string}> {
        return requester<{data: OvernattingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OvernattingConnectionQueryVariables, query: string}, OvernattingConnectionQueryVariables>(OvernattingConnectionDocument, variables, options);
      },
    kulturformidling(variables: KulturformidlingQueryVariables, options?: C): Promise<{data: KulturformidlingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KulturformidlingQueryVariables, query: string}> {
        return requester<{data: KulturformidlingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KulturformidlingQueryVariables, query: string}, KulturformidlingQueryVariables>(KulturformidlingDocument, variables, options);
      },
    kulturformidlingConnection(variables?: KulturformidlingConnectionQueryVariables, options?: C): Promise<{data: KulturformidlingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KulturformidlingConnectionQueryVariables, query: string}> {
        return requester<{data: KulturformidlingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KulturformidlingConnectionQueryVariables, query: string}, KulturformidlingConnectionQueryVariables>(KulturformidlingConnectionDocument, variables, options);
      },
    krambu(variables: KrambuQueryVariables, options?: C): Promise<{data: KrambuQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KrambuQueryVariables, query: string}> {
        return requester<{data: KrambuQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KrambuQueryVariables, query: string}, KrambuQueryVariables>(KrambuDocument, variables, options);
      },
    krambuConnection(variables?: KrambuConnectionQueryVariables, options?: C): Promise<{data: KrambuConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KrambuConnectionQueryVariables, query: string}> {
        return requester<{data: KrambuConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KrambuConnectionQueryVariables, query: string}, KrambuConnectionQueryVariables>(KrambuConnectionDocument, variables, options);
      },
    bilder(variables: BilderQueryVariables, options?: C): Promise<{data: BilderQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BilderQueryVariables, query: string}> {
        return requester<{data: BilderQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BilderQueryVariables, query: string}, BilderQueryVariables>(BilderDocument, variables, options);
      },
    bilderConnection(variables?: BilderConnectionQueryVariables, options?: C): Promise<{data: BilderConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BilderConnectionQueryVariables, query: string}> {
        return requester<{data: BilderConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BilderConnectionQueryVariables, query: string}, BilderConnectionQueryVariables>(BilderConnectionDocument, variables, options);
      },
    referanser(variables: ReferanserQueryVariables, options?: C): Promise<{data: ReferanserQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReferanserQueryVariables, query: string}> {
        return requester<{data: ReferanserQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReferanserQueryVariables, query: string}, ReferanserQueryVariables>(ReferanserDocument, variables, options);
      },
    referanserConnection(variables?: ReferanserConnectionQueryVariables, options?: C): Promise<{data: ReferanserConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReferanserConnectionQueryVariables, query: string}> {
        return requester<{data: ReferanserConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReferanserConnectionQueryVariables, query: string}, ReferanserConnectionQueryVariables>(ReferanserConnectionDocument, variables, options);
      },
    nyheter(variables: NyheterQueryVariables, options?: C): Promise<{data: NyheterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NyheterQueryVariables, query: string}> {
        return requester<{data: NyheterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NyheterQueryVariables, query: string}, NyheterQueryVariables>(NyheterDocument, variables, options);
      },
    nyheterConnection(variables?: NyheterConnectionQueryVariables, options?: C): Promise<{data: NyheterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NyheterConnectionQueryVariables, query: string}> {
        return requester<{data: NyheterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NyheterConnectionQueryVariables, query: string}, NyheterConnectionQueryVariables>(NyheterConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  